services:
  web:
    build:
      context:
        .
      # args: # use this to test bucket prefix substitution or leave commented out to serve assets from the container.
      #   ASSET_BUCKET_URL: https://storage.googleapis.com/nf-site-assets-staging
    ports:
      - "8080:8080"
    environment:
      # In Docker Compose, hostnames are service names.
      - REDIS_URL=redis://redis:6379
      - GOOGLE_CLOUD_PROJECT=nf-web-480214
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
      - DATABASE_URL=postgresql+asyncpg://local_user:tension_is_all_you_need@postgres:5432/neufangled_local
    volumes:
      - ${HOME}/.config/gcloud/application_default_credentials.json:/app/service-account.json
    depends_on:
      - redis
      - postgres

  redis:
    image: "redis:alpine"

  media_gateway:
    build: media_gateway
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8189:8189/udp"
    environment:
      - WEBRTC_USE_HTTPS=no
      - CONTROL_PLANE_API_URL=http://web:8080
      - WEBRTC_ADDITIONAL_HOSTS=[]

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: neufangled_local
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: "tension_is_all_you_need"
    ports:
      - "5432:5432"
    volumes:
      - ./local_db_data:/var/lib/postgresql/data