services:
  web:
    build:
      context:
        .
      # args: # use this to test bucket prefix substitution or leave commented out to serve assets from the container.
      #   ASSET_BUCKET_URL: https://storage.googleapis.com/nf-site-assets-staging
    ports:
      - "8080:8080"
    environment:
      # In Docker Compose, hostnames are service names.
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

  media_gateway:
    build: media_gateway
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8189:8189/udp"
    environment:
      - WEBRTC_USE_HTTPS=no
      - CONTROL_PLANE_API_URL=http://web:8080
      - WEBRTC_ADDITIONAL_HOSTS=[]